package me.luchs.aoc2024

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.*

class DayEightTest {

    val example = """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    """.trimIndent()

    val example2 = """
        T.........
        ...T......
        .T........
        ..........
        ..........
        ..........
        ..........
        ..........
        ..........
        ..........
    """.trimIndent()

    @Test
    fun partOne() {
        val result = DayEight(example).partOne()
        assertEquals(14, result)
    }

    @Test
    fun partTwo() {
        val result = DayEight(example).partTwo()
        assertEquals(34, result)
    }

    @Test
    fun partTwoExample2() {
        val result = DayEight(example2).partTwo()
        assertEquals(9, result)
    }

}